'use strict';

module.exports = {
  async up(queryInterface, Sequelize) {

    await queryInterface.bulkInsert('options', [
      //Tributario
      { order: 1, answer: "Sí", score: 10, question_id: 1 },
      { order: 2, answer: "¿Algunas?", score: 5, question_id: 1 },
      { order: 3, answer: "No", score: 0, question_id: 1 },
      { order: 1, answer: "Sí, siempre", score: 10, question_id: 2 },
      { order: 2, answer: "En su mayoría", score: 7.5, question_id: 2 },
      { order: 3, answer: "A veces", score: 5, question_id: 2 },
      { order: 4, answer: "Raramente", score: 2.5, question_id: 2 },
      { order: 5, answer: "No, nunca", score: 0, question_id: 2 },
      { order: 1, answer: "Siempre estamos buscando oportunidades", score: 10, question_id: 3 },
      { order: 2, answer: "Con regularidad", score: 7.5, question_id: 3 },
      { order: 3, answer: "Ocasionalmente", score: 5, question_id: 3 },
      { order: 4, answer: "Raramente", score: 2.5, question_id: 3 },
      { order: 5, answer: "Nunca lo hacemos", score: 0, question_id: 3 },
      //Planificación estratégica
      { order: 1, answer: "Totalmente clara", score: 10, question_id: 4 },
      { order: 2, answer: "Bastante clara", score: 7.5, question_id: 4 },
      { order: 3, answer: "Algo clara", score: 5, question_id: 4 },
      { order: 4, answer: "Poco clara", score: 2.5, question_id: 4 },
      { order: 5, answer: "No hay una visión clara", score: 0, question_id: 4 },
      { order: 1, answer: "Sí, de manera exhaustiva", score: 10, question_id: 5 },
      { order: 2, answer: "Sí, pero podría mejorar", score: 7.5, question_id: 5 },
      { order: 3, answer: "A veces", score: 5, question_id: 5 },
      { order: 4, answer: "Raramente", score: 2.5, question_id: 5 },
      { order: 5, answer: "No realizamos planificación estratégica", score: 0, question_id: 5 },
      { order: 1, answer: "Siempre se comunica claramente", score: 10, question_id: 6 },
      { order: 2, answer: "En su mayoría se comunica", score: 7.5, question_id: 6 },
      { order: 3, answer: "A veces se comunica", score: 5, question_id: 6 },
      { order: 4, answer: "Raramente se comunica", score: 2.5, question_id: 6 },
      { order: 5, answer: "No se comunica adecuadamente", score: 0, question_id: 6 },
      //KPI (Indicadores Clave de Rendimiento)
      { order: 1, answer: "Sí, y están alineados con nuestros objetivos", score: 10, question_id: 7 },
      { order: 2, answer: "En su mayoría, pero podrían ser más específicos", score: 7.5, question_id: 7 },
      { order: 3, answer: "Algunos, pero no son consistentes", score: 5, question_id: 7 },
      { order: 4, answer: "Raramente identificamos KPI", score: 2.5, question_id: 7 },
      { order: 5, answer: "No tenemos KPI establecidos", score: 0, question_id: 7 },
      { order: 1, answer: "Siempre se actualizan según sea necesario", score: 10, question_id: 8 },
      { order: 2, answer: "Con regularidad, pero podríamos mejorar", score: 7.5, question_id: 8 },
      { order: 3, answer: "A veces se actualizan", score: 5, question_id: 8 },
      { order: 4, answer: "Raramente se actualizan", score: 2.5, question_id: 8 },
      { order: 5, answer: "No se actualizan en absoluto", score: 0, question_id: 8 },
      { order: 1, answer: "Sí, tenemos un sistema eficiente", score: 10, question_id: 9 },
      { order: 2, answer: "En su mayoría, pero hay áreas de mejora", score: 7.5, question_id: 9 },
      { order: 3, answer: "Existe, pero no es consistente", score: 5, question_id: 9 },
      { order: 4, answer: "Raramente seguimos el cumplimiento de los KPI", score: 2.5, question_id: 9 },
      { order: 5, answer: "No tenemos un sistema claro", score: 0, question_id: 9 },
      //Desarrollo de Equipos
      { order: 1, answer: "Siempre promovemos la colaboración", score: 10, question_id: 10 },
      { order: 2, answer: "En su mayoría, pero hay excepciones", score: 7.5, question_id: 10 },
      { order: 3, answer: "A veces promovemos la colaboración", score: 5, question_id: 10 },
      { order: 4, answer: "Raramente promovemos la colaboración", score: 2.5, question_id: 10 },
      { order: 5, answer: "No fomentamos la colaboración", score: 0, question_id: 10 },
      { order: 1, answer: "Sí, de manera regular y personalizada", score: 10, question_id: 11 },
      { order: 2, answer: "En su mayoría, pero podría ser más frecuente", score: 7.5, question_id: 11 },
      { order: 3, answer: "Ocasionalmente proporcionamos formación", score: 5, question_id: 11 },
      { order: 4, answer: "Raramente proporcionamos formación", score: 2.5, question_id: 11 },
      { order: 5, answer: "No ofrecemos formación continua", score: 0, question_id: 11 },
      { order: 1, answer: "Sí, tenemos un sistema estructurado", score: 10, question_id: 12 },
      { order: 2, answer: "En su mayoría, pero podría mejorarse", score: 7.5, question_id: 12 },
      { order: 3, answer: "Existe, pero no es consistente", score: 5, question_id: 12 },
      { order: 4, answer: "Raramente damos retroalimentación", score: 2.5, question_id: 12 },
      { order: 5, answer: "No hay un sistema de retroalimentación", score: 0, question_id: 12 },
      //Ventas
      { order: 1, answer: "Sí, con un proceso claro y efectivo", score: 10, question_id: 13 },
      { order: 2, answer: "En su mayoría, aunque podría ser más estructurado", score: 7.5, question_id: 13 },
      { order: 3, answer: "Existe, pero no se sigue consistentemente", score: 5, question_id: 13 },
      { order: 4, answer: "No hay un proceso definido", score: 2.5, question_id: 13 },
      { order: 5, answer: "No se sigue ningún proceso de ventas", score: 0, question_id: 13 },
      { order: 1, answer: "Sí, regularmente y adaptada a las necesidades individuales", score: 10, question_id: 14 },
      { order: 2, answer: "En su mayoría, pero podría ser más frecuente", score: 7.5, question_id: 14 },
      { order: 3, answer: "Ocasionalmente proporcionamos formación", score: 5, question_id: 14 },
      { order: 4, answer: "Raramente se brinda capacitación", score: 2.5, question_id: 14 },
      { order: 5, answer: "No se ofrece capacitación al equipo de ventas", score: 0, question_id: 14 },
      { order: 1, answer: "Sí, con indicadores específicos y actualizados", score: 10, question_id: 15 },
      { order: 2, answer: "En su mayoría, pero podríamos mejorar el análisis", score: 7.5, question_id: 15 },
      { order: 3, answer: "A veces se realizan seguimientos de métricas", score: 5, question_id: 15 },
      { order: 4, answer: "Raramente se analizan métricas de ventas", score: 2.5, question_id: 15 },
      { order: 5, answer: "No se hace ningún seguimiento de métricas de ventas", score: 0, question_id: 15 },
      //MKT
      { order: 1, answer: "Si", score: 10, question_id: 16 },
      { order: 2, answer: "No", score: 0, question_id: 16 },
      { order: 1, answer: "Muy efectivas", score: 10, question_id: 17 },
      { order: 2, answer: "Efectivas en su mayoría", score: 7.5, question_id: 17 },
      { order: 3, answer: "Moderadamente efectivas", score: 5, question_id: 17 },
      { order: 4, answer: "Poco efectivas", score: 2.5, question_id: 17 },
      { order: 5, answer: "No realizo", score: 0, question_id: 17 },
      { order: 1, answer: "Si", score: 10, question_id: 18 },
      { order: 2, answer: "No", score: 0, question_id: 18 },
    ]);
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('options', null, { truncate: true, cascade: true });
  }
};
